<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SimStock</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Another-Mirai-Native.Abstractions" Version="1.2.1" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.214" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TdxProtocol\TdxProtocol.csproj" />
  </ItemGroup>

</Project>
